OpenLiberty/guide-bean-validation

README.adoc

Fix test file paths in readme

---

README.adoc
finish/src/main/java/io/openliberty/guides/beanvalidation/SerialNumber.java
finish/src/main/webapp/index.xhtml
finish/src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java
start/src/main/webapp/index.xhtml

Updates from the feedback in #9.  I have address all the issues except the title of the guide, which I'm waiting for more feedback on.

Updates from feedback

---

README.adoc

ID review edits.

---

README.adoc

Updates from comments on ID review, fixing spacing, and fresh user feedback freview.

Updates from reviews

---

README.adoc

Updates based on feedback in issue #11 and wrapping lines at 88 characters.

Review updates from issue 11

---

README.adoc

Update the title and references throughout the guide to match the guide's updated focus on bean validation.

Update title and remove application references

---

README.adoc
finish/src/main/java/io/openliberty/guides/beanvalidation/BeanValidationEndpoint.java

Remove the period from the post section of the OpenAPI site and README.

Remove period from OpenAPI post section

---

README.adoc

Updates based on feedback raised in issue #22.

Updates based on feedback in #22

---

README.adoc

Update the guide's release date so it is sorted to the front of the list on openliberty.io

Update release date of this guide

---

README.adoc

Update SEO title to better reflect what we have.

Fix SEO title

---

finish/src/main/java/io/openliberty/guides/beanvalidation/BeanValidationEndpoint.java

fixing https://github.com/OpenLiberty/guide-bean-validation/issues/43

Fixing method closing bracket

---

.travis.yml

- Fixed issue #49, see explanation in the issue.

Fix auto test

---

finish/src/main/java/io/openliberty/guides/beanvalidation/BeanValidationEndpoint.java
finish/src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java

Tested changes on `qa` branch in https://travis-ci.org/OpenLiberty/guide-bean-validation/jobs/530430052

Qa to Master: added dist in travis.yml to run jdk8 tests

---

.travis.yml
finish/pom.xml
start/pom.xml

Reduce the SRVE9967W warnings from the messages.log
#52

Merge qa to master: Updated dependencies

---

README.adoc

Gkwan ibm patch 1

---

README.adoc
finish/pom.xml
finish/src/main/java/io/openliberty/guides/beanvalidation/Astronaut.java
finish/src/main/java/io/openliberty/guides/beanvalidation/BeanValidationEndpoint.java
finish/src/main/java/io/openliberty/guides/beanvalidation/SerialNumber.java
finish/src/main/java/io/openliberty/guides/beanvalidation/SerialNumberValidator.java
finish/src/main/java/io/openliberty/guides/beanvalidation/Spacecraft.java
finish/src/main/liberty/config/server.xml
finish/src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java
start/pom.xml
start/src/main/liberty/config/server.xml

https://github.com/OpenLiberty/guides-common/issues/352
https://github.com/OpenLiberty/guides-common/issues/308

hotspot and name convention update 

---

finish/src/main/java/io/openliberty/guides/beanvalidation/BeanValidationEndpoint.java

https://github.com/OpenLiberty/guide-bean-validation/pull/56

spacing fix 

---

.travis.yml
README.adoc
finish/pom.xml
finish/src/main/java/io/openliberty/guides/beanvalidation/Astronaut.java
finish/src/main/java/io/openliberty/guides/beanvalidation/BeanValidationEndpoint.java
finish/src/main/java/io/openliberty/guides/beanvalidation/SerialNumber.java
finish/src/main/java/io/openliberty/guides/beanvalidation/SerialNumberValidator.java
finish/src/main/java/io/openliberty/guides/beanvalidation/Spacecraft.java
finish/src/main/liberty/config/server.xml
finish/src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java
start/pom.xml
start/src/main/liberty/config/server.xml

Merge qa to master: update hotspot and artifactId

---

finish/src/main/java/io/openliberty/guides/beanvalidation/Astronaut.java
finish/src/main/java/io/openliberty/guides/beanvalidation/BeanValidationEndpoint.java

Addressing:
- https://github.com/OpenLiberty/guide-bean-validation/issues/62
- https://github.com/OpenLiberty/guide-bean-validation/issues/61

fix spacing

---

README.adoc
finish/pom.xml
start/pom.xml

Merge qa to master: update versions

---

finish/pom.xml
start/pom.xml

- Plugin versions specified at plugin
- Changed Jakarta api dependancy

Updated jakarta dependancy, updated plugin versions to best practices

---

finish/pom.xml
start/pom.xml

Merge qa to master: specify version directly in the plugins  

---

.travis.yml
finish/pom.xml
start/pom.xml

Merge qa to master: fix travis automation

---

.travis.yml

- https://github.com/OpenLiberty/guides-common/issues/497
- https://github.com/OpenLiberty/guides-common/issues/500

Fix the travis.yml

---

.travis.yml
README.adoc

Merge qa to master: remove non-inclusive terms

---

.github/workflows/test.yml

Issue: https://github.com/OpenLiberty/guides-common/issues/532

Merge qa to master: Update test.yml (#89)
